/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Report whether the process is alive
         * @description Checks nothing outside the process. A liveness probe that queries the database restarts the application every time the database blinks, which turns a recoverable problem into an outage.
         */
        get: operations["live"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Report whether this instance should receive traffic
         * @description Answers 503 while the database does not respond, and from the moment the instance is told to stop — so the platform takes it out of rotation before it closes.
         */
        get: operations["ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in
         * @description Set `transport` to `cookie` (the default) to receive HttpOnly cookies and an empty token body, or to `header` to receive the tokens in the response body for a client that cannot use cookies.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate the refresh token
         * @description Reads the refresh token from its cookie, or from the body for a header client. The presented token is invalidated; presenting it a second time revokes every token descended from that sign-in.
         */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign out
         * @description Always answers 204 and always clears the cookies, with or without valid credentials — a client that cannot sign out would otherwise keep retrying with the credential it is trying to drop. The whole family descended from that sign-in is revoked.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read the signed-in session
         * @description Who is signed in, the permissions their access token carries, and when that token expires. A browser client cannot read its HttpOnly token, so this is where it learns all three — on load, and again after every refresh. Answers 401 when the account behind a still-valid token has been suspended or deleted.
         */
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/maintenance/prune-expired-tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run the expired-token prune now
         * @description The same work the nightly schedule does, triggered by hand — for a backlog that should not wait for the next run. Answers how many records were removed. Overlapping the schedule is harmless: both delete the same expired records, by id. Requires the operator key in `x-admin-api-key`; no role grants it.
         */
        post: operations["pruneExpiredTokens"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List users
         * @description Requires the `users:read` permission. Offset paging: `page` and `limit`.
         */
        get: operations["getUsers"];
        put?: never;
        /**
         * Create a user
         * @description Requires the `users:create` permission.
         */
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a user by id
         * @description Requires the `users:read` permission.
         */
        get: operations["getUserById"];
        put?: never;
        post?: never;
        /**
         * Delete a user
         * @description Requires the `users:delete` permission.
         */
        delete: operations["deleteUser"];
        options?: never;
        head?: never;
        /**
         * Update a user
         * @description Requires the `users:update` permission.
         */
        patch: operations["updateUser"];
        trace?: never;
    };
    "/api/v1/users/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change the signed-in user's password */
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change the signed-in user's preferences
         * @description The language is the account's: every message sent to the user is written in it, and a client applies it after sign-in. Setting the value it already has changes nothing.
         */
        patch: operations["updatePreferences"];
        trace?: never;
    };
    "/api/v1/users/{id}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Replace a user's roles
         * @description Requires the `users:assign_roles` permission.
         */
        patch: operations["assignUserRoles"];
        trace?: never;
    };
    "/api/v1/users/{id}/suspend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Suspend a user
         * @description The user can no longer sign in or refresh, and every session they hold is revoked. An access token already issued keeps working until it expires. Suspending a suspended user changes nothing. Requires the `users:suspend` permission.
         */
        post: operations["suspendUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}/reactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reactivate a suspended user
         * @description The user signs in again; the sessions revoked by the suspension stay revoked. Requires the `users:suspend` permission.
         */
        post: operations["reactivateUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List roles
         * @description Requires the `roles:read` permission. Offset paging: `page` and `limit`.
         */
        get: operations["getRoles"];
        put?: never;
        /**
         * Create a role
         * @description Requires the `roles:create` permission.
         */
        post: operations["createRole"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a role by id
         * @description Requires the `roles:read` permission.
         */
        get: operations["getRoleById"];
        put?: never;
        post?: never;
        /**
         * Delete a role
         * @description Soft deletes the role. Users who already hold it keep their permissions until the next token, because the set is resolved at sign-in. Requires the `roles:delete` permission.
         */
        delete: operations["deleteRole"];
        options?: never;
        head?: never;
        /**
         * Update a role
         * @description Requires the `roles:update` permission.
         */
        patch: operations["updateRole"];
        trace?: never;
    };
    "/api/v1/files/upload-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask for somewhere to upload
         * @description The bytes never pass through this API: it answers with a URL to upload them to directly, with the accepted type and size pinned into it, so the storage provider rejects anything else. Confirm the upload once the bytes are sent; until then the file cannot be downloaded, and an upload nobody confirms is removed after a day. Requires the `files:create` permission.
         */
        post: operations["requestUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/{id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm that the bytes were uploaded
         * @description Checks with storage that an object exists under the file's key with the declared size and type, and only then makes the file downloadable. Confirming twice changes nothing. Requires the `files:create` permission.
         */
        post: operations["confirmUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/{id}/download-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a link to a stored file
         * @description A file the caller may not see answers 404, not 403 — a 403 would confirm it exists. The link serves the file as an attachment, under the type it was accepted with. Requires the `files:read` permission.
         */
        get: operations["getDownloadUrl"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: {
        ProblemFieldErrorDto: {
            /**
             * @description The rejected field, as a dotted path for a nested one
             * @example price.amountMinor
             */
            field: string;
            /**
             * @description Why it was rejected, translated
             * @example The amount must be a whole number
             */
            message: string;
        };
        ProblemDetailsDto: {
            /** @example about:blank */
            type: string;
            /**
             * @description The status phrase, translated
             * @example Not Found
             */
            title: string;
            /** @example 404 */
            status: number;
            /**
             * @description What went wrong, translated
             * @example User not found
             */
            detail: string;
            /**
             * @description The path that was requested
             * @example /api/v1/users/01890a5d-ac96-774b-bcce-b302099a8057
             */
            instance: string;
            /**
             * @description The stable identifier a client branches on
             * @example users.user_not_found
             */
            code: string;
            /**
             * @description The same id as the x-trace-id response header
             * @example 4bf92f3577b34da6a3ce929d0e0e4736
             */
            traceId: string;
            /** @description Every rejected field; empty unless validation failed */
            errors: components["schemas"]["ProblemFieldErrorDto"][];
        };
        AuthTokensDto: {
            /**
             * @description Present only for a header client
             * @example null
             */
            accessToken: string | null;
            /**
             * @description Present only for a header client
             * @example null
             */
            refreshToken: string | null;
            /**
             * Format: date-time
             * @example 2026-02-15T10:30:00.000Z
             */
            expiresAt: string;
        };
        LoginDto: {
            /** @example admin@example.com */
            email: string;
            /** @example Change-me-1! */
            password: string;
            /**
             * @description Where to put the tokens. Defaults to cookie.
             * @enum {string}
             */
            transport?: "cookie" | "header";
        };
        RefreshTokenDto: {
            /** @description Required only when the refresh token is not in a cookie */
            refreshToken?: string;
        };
        LogoutDto: {
            /** @description Required only when the refresh token is not in a cookie */
            refreshToken?: string;
        };
        SessionUserDto: {
            /** @example 01890a5d-ac96-774b-bcce-b302099a8057 */
            id: string;
            /** @example Jane Doe */
            name: string;
            /**
             * Format: email
             * @example jane@example.com
             */
            email: string;
            /**
             * @example en
             * @enum {string}
             */
            preferredLanguage: "en" | "es";
        };
        SessionDto: {
            user: components["schemas"]["SessionUserDto"];
            /**
             * @description The permissions the access token carries: what the API allows until the next refresh
             * @example [
             *       "users:read"
             *     ]
             */
            permissions: ("users:read" | "users:create" | "users:update" | "users:delete" | "users:assign_roles" | "users:suspend" | "roles:read" | "roles:create" | "roles:update" | "roles:delete" | "files:create" | "files:read")[];
            /**
             * Format: date-time
             * @description When the access token stops being accepted; refreshing before then avoids a 401
             * @example 2026-02-15T10:45:00.000Z
             */
            accessTokenExpiresAt: string;
        };
        PruneResultDto: {
            /**
             * @description How many expired records were removed
             * @example 42
             */
            deleted: number;
        };
        UserDto: {
            /** @example 01890a5d-ac96-774b-bcce-b302099a8057 */
            id: string;
            /** @example Jane Doe */
            name: string;
            /**
             * Format: email
             * @example jane@example.com
             */
            email: string;
            /**
             * @example active
             * @enum {string}
             */
            status: "active" | "suspended";
            /**
             * @example [
             *       "01890a5d-ac96-774b-bcce-b302099a8058"
             *     ]
             */
            roleIds: string[];
            /**
             * @example en
             * @enum {string}
             */
            preferredLanguage: "en" | "es";
            /**
             * Format: date-time
             * @example 2026-01-15T10:30:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2026-01-20T14:45:00.000Z
             */
            updatedAt: string;
            /**
             * Format: date-time
             * @example null
             */
            deletedAt: string | null;
        };
        ApiPagination: {
            /**
             * @description Total number of items across all pages
             * @example 100
             */
            total: number;
            /**
             * @description Total number of pages available
             * @example 10
             */
            pages: number;
            /**
             * @description Current page number (1-based)
             * @example 2
             */
            page: number;
            /**
             * @description Number of items per page
             * @example 10
             */
            limit: number;
            /**
             * @description Next page number
             * @example 3
             */
            next: number | null;
            /**
             * @description Previous page number
             * @example 1
             */
            previous: number | null;
        };
        CreatedDto: {
            /** @example 01890a5d-ac96-774b-bcce-b302099a8057 */
            id: string;
        };
        CreateUserDto: {
            /** @example Jane Doe */
            name: string;
            /** @example jane@example.com */
            email: string;
            /**
             * @description At most 72 bytes: bcrypt ignores anything beyond that
             * @example Change-me-1!
             */
            password: string;
            /** @enum {string} */
            preferredLanguage?: "en" | "es";
        };
        UpdateUserDto: {
            /** @example jane@example.com */
            email?: string;
        };
        ChangePasswordDto: {
            /** @example Change-me-1! */
            currentPassword: string;
            /** @example An0ther-one! */
            newPassword: string;
        };
        UpdatePreferencesDto: {
            /**
             * @description The language every message to this account is written in
             * @enum {string}
             */
            preferredLanguage: "en" | "es";
        };
        AssignUserRolesDto: {
            /**
             * @example [
             *       "01890a5d-ac96-774b-bcce-b302099a8057"
             *     ]
             */
            roleIds: string[];
        };
        RoleDto: {
            /** @example 01890a5d-ac96-774b-bcce-b302099a8057 */
            id: string;
            /** @example Support Agent */
            name: string;
            /** @example Reads and updates users */
            description: string | null;
            /**
             * @example [
             *       "users:read"
             *     ]
             */
            permissions: ("users:read" | "users:create" | "users:update" | "users:delete" | "users:assign_roles" | "users:suspend" | "roles:read" | "roles:create" | "roles:update" | "roles:delete" | "files:create" | "files:read")[];
            /**
             * Format: date-time
             * @example 2026-01-15T10:30:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2026-01-20T14:45:00.000Z
             */
            updatedAt: string;
        };
        CreateRoleDto: {
            /** @example Support Agent */
            name: string;
            /** @example Reads and updates users */
            description?: string;
            /**
             * @example [
             *       "users:read"
             *     ]
             */
            permissions: ("users:read" | "users:create" | "users:update" | "users:delete" | "users:assign_roles" | "users:suspend" | "roles:read" | "roles:create" | "roles:update" | "roles:delete" | "files:create" | "files:read")[];
        };
        UpdateRoleDto: {
            /** @example Support Agent */
            name?: string;
            /**
             * @description Send null to remove the description
             * @example Reads and updates users
             */
            description?: string | null;
            /**
             * @example [
             *       "users:read"
             *     ]
             */
            permissions?: ("users:read" | "users:create" | "users:update" | "users:delete" | "users:assign_roles" | "users:suspend" | "roles:read" | "roles:create" | "roles:update" | "roles:delete" | "files:create" | "files:read")[];
        };
        RequestedUploadDto: {
            /** @example 01890a5d-ac96-774b-bcce-b302099a8057 */
            fileId: string;
            /** @description Upload the bytes here with a PUT. It expires. */
            uploadUrl: string;
            /**
             * @description Send exactly this many bytes: the size is signed into the URL, so any other length is rejected
             * @example 204800
             */
            declaredBytes: number;
        };
        RequestUploadDto: {
            /** @enum {string} */
            contentType: "image/png" | "image/jpeg" | "application/pdf";
            /** @example 204800 */
            declaredBytes: number;
            /** @example contract.pdf */
            originalName: string;
        };
        DownloadUrlDto: {
            /** @description Short-lived link to the stored bytes */
            downloadUrl: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
};
export type ProblemFieldErrorDto = components['schemas']['ProblemFieldErrorDto'];
export type ProblemDetailsDto = components['schemas']['ProblemDetailsDto'];
export type AuthTokensDto = components['schemas']['AuthTokensDto'];
export type LoginDto = components['schemas']['LoginDto'];
export type RefreshTokenDto = components['schemas']['RefreshTokenDto'];
export type LogoutDto = components['schemas']['LogoutDto'];
export type SessionUserDto = components['schemas']['SessionUserDto'];
export type SessionDto = components['schemas']['SessionDto'];
export type PruneResultDto = components['schemas']['PruneResultDto'];
export type UserDto = components['schemas']['UserDto'];
export type ApiPagination = components['schemas']['ApiPagination'];
export type CreatedDto = components['schemas']['CreatedDto'];
export type CreateUserDto = components['schemas']['CreateUserDto'];
export type UpdateUserDto = components['schemas']['UpdateUserDto'];
export type ChangePasswordDto = components['schemas']['ChangePasswordDto'];
export type UpdatePreferencesDto = components['schemas']['UpdatePreferencesDto'];
export type AssignUserRolesDto = components['schemas']['AssignUserRolesDto'];
export type RoleDto = components['schemas']['RoleDto'];
export type CreateRoleDto = components['schemas']['CreateRoleDto'];
export type UpdateRoleDto = components['schemas']['UpdateRoleDto'];
export type RequestedUploadDto = components['schemas']['RequestedUploadDto'];
export type RequestUploadDto = components['schemas']['RequestUploadDto'];
export type DownloadUrlDto = components['schemas']['DownloadUrlDto'];
export type $defs = Record<string, never>;
export interface operations {
    live: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description The Health Check is successful
             *
             *     The process is running
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status?: string;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        info?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /** @example {} */
                        error?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        details?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
            /** @description The Health Check is not successful */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example error */
                        status?: string;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        info?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "redis": {
                         *         "status": "down",
                         *         "message": "Could not connect"
                         *       }
                         *     }
                         */
                        error?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       },
                         *       "redis": {
                         *         "status": "down",
                         *         "message": "Could not connect"
                         *       }
                         *     }
                         */
                        details?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
        };
    };
    ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description The Health Check is successful
             *
             *     Ready to serve traffic
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status?: string;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        info?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /** @example {} */
                        error?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        details?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
            /**
             * @description The Health Check is not successful
             *
             *     Not ready: shutting down, or the database is unreachable
             */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example error */
                        status?: string;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        info?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "redis": {
                         *         "status": "down",
                         *         "message": "Could not connect"
                         *       }
                         *     }
                         */
                        error?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       },
                         *       "redis": {
                         *         "status": "down",
                         *         "message": "Could not connect"
                         *       }
                         *     }
                         */
                        details?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            /** @description Signed in */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AuthTokensDto"];
                    };
                };
            };
            /** @description The body is not valid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Too many attempts from this address or for this account */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenDto"];
            };
        };
        responses: {
            /** @description Rotated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AuthTokensDto"];
                    };
                };
            };
            /** @description The body is not valid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description The token is unknown, expired, or was already used */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Too many attempts from this address */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutDto"];
            };
        };
        responses: {
            /** @description Signed out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The body is not valid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["SessionDto"];
                    };
                };
            };
            /** @description No valid credentials were presented, or the account is no longer active */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    pruneExpiredTokens: {
        parameters: {
            query?: never;
            header: {
                /** @description Operator key */
                "x-admin-api-key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The prune ran */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PruneResultDto"];
                    };
                };
            };
            /** @description The operator key is missing or wrong */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    getUsers: {
        parameters: {
            query?: {
                /** @description Page number (1-based) */
                page?: number;
                /** @description Number of items per page */
                limit?: number;
                /** @description Filter by specific IDs. Accepts comma-separated string or repeated query params. */
                ids?: string;
                /** @description Filter by creation date — lower bound (inclusive). ISO 8601 format. */
                createdAtFrom?: string;
                /** @description Filter by creation date — upper bound (inclusive). ISO 8601 format. */
                createdAtTo?: string;
                /** @description Sort direction */
                sortOrder?: "asc" | "desc";
                /** @description Matches the name or the email */
                search?: string;
                status?: "active" | "suspended";
                roleId?: string;
                sortBy?: "createdAt" | "name" | "email";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of users */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["UserDto"][];
                        pagination: components["schemas"]["ApiPagination"];
                    };
                };
            };
            /** @description A query parameter is not valid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description No valid credentials were presented */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Missing the required permission */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserDto"];
            };
        };
        responses: {
            /** @description User created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CreatedDto"];
                    };
                };
            };
            /** @description The body is not valid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description No valid credentials were presented */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Missing the required permission */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description The email is already registered */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    getUserById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["UserDto"];
                    };
                };
            };
            /** @description No valid credentials were presented */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Missing the required permission */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description No user matches the id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No valid credentials were presented */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Missing the required permission */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description No user matches the id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserDto"];
            };
        };
        responses: {
            /** @description User updated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The body is not valid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description No valid credentials were presented */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Missing the required permission */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description No user matches the id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description The email is already registered */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordDto"];
            };
        };
        responses: {
            /** @description Password changed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The body is not valid, or the current password is incorrect */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description No valid credentials were presented */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Missing the required permission */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    updatePreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePreferencesDto"];
            };
        };
        responses: {
            /** @description Preferences changed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The body is not valid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description No valid credentials were presented */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Missing the required permission */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description The account is suspended */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    assignUserRoles: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignUserRolesDto"];
            };
        };
        responses: {
            /** @description Roles assigned */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The body is not valid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description No valid credentials were presented */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Missing the required permission */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description No user matches the id, or one of the roles does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    suspendUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User suspended */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No valid credentials were presented */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Missing the required permission */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description No user matches the id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    reactivateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User reactivated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No valid credentials were presented */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Missing the required permission */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description No user matches the id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    getRoles: {
        parameters: {
            query?: {
                /** @description Page number (1-based) */
                page?: number;
                /** @description Number of items per page */
                limit?: number;
                /** @description Filter by specific IDs. Accepts comma-separated string or repeated query params. */
                ids?: string;
                /** @description Filter by creation date — lower bound (inclusive). ISO 8601 format. */
                createdAtFrom?: string;
                /** @description Filter by creation date — upper bound (inclusive). ISO 8601 format. */
                createdAtTo?: string;
                /** @description Sort direction */
                sortOrder?: "asc" | "desc";
                /** @description Matches the name */
                search?: string;
                sortBy?: "createdAt" | "name";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of roles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["RoleDto"][];
                        pagination: components["schemas"]["ApiPagination"];
                    };
                };
            };
            /** @description A query parameter is not valid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description No valid credentials were presented */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Missing the required permission */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    createRole: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRoleDto"];
            };
        };
        responses: {
            /** @description Role created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CreatedDto"];
                    };
                };
            };
            /** @description The body is not valid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description No valid credentials were presented */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Missing the required permission */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description A role with that name already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    getRoleById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The role */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["RoleDto"];
                    };
                };
            };
            /** @description No valid credentials were presented */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Missing the required permission */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description No role matches the id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    deleteRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Role deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No valid credentials were presented */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Missing the required permission */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description No role matches the id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    updateRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRoleDto"];
            };
        };
        responses: {
            /** @description Role updated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The body is not valid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description No valid credentials were presented */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Missing the required permission */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description No role matches the id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description A role with that name already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    requestUpload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestUploadDto"];
            };
        };
        responses: {
            /** @description Upload authorised */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["RequestedUploadDto"];
                    };
                };
            };
            /** @description The type is not accepted, or the size is too large */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description No valid credentials were presented */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Missing the required permission */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    confirmUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Upload confirmed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No valid credentials were presented */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Missing the required permission */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description No file matches the id, or it is not the caller's */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Nothing was uploaded yet, or what was uploaded is not what was declared */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    getDownloadUrl: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The link */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["DownloadUrlDto"];
                    };
                };
            };
            /** @description No valid credentials were presented */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Missing the required permission */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description No file matches the id, or it is not the caller's */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description The upload was never confirmed */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
}
type FlattenedDeepRequired<T> = {
    [K in keyof T]-?: FlattenedDeepRequired<T[K] extends unknown[] | undefined | null ? Extract<T[K], unknown[]>[number] : T[K]>;
};
type ReadonlyArray<T> = [
    Exclude<T, undefined>
] extends [
    unknown[]
] ? Readonly<Exclude<T, undefined>> : Readonly<Exclude<T, undefined>[]>;
export const pathsApiV1UsersGetParametersQuerySortOrderValues: ReadonlyArray<FlattenedDeepRequired<paths>["/api/v1/users"]["get"]["parameters"]["query"]["sortOrder"]> = ["asc", "desc"];
export const pathsApiV1UsersGetParametersQueryStatusValues: ReadonlyArray<FlattenedDeepRequired<paths>["/api/v1/users"]["get"]["parameters"]["query"]["status"]> = ["active", "suspended"];
export const pathsApiV1UsersGetParametersQuerySortByValues: ReadonlyArray<FlattenedDeepRequired<paths>["/api/v1/users"]["get"]["parameters"]["query"]["sortBy"]> = ["createdAt", "name", "email"];
export const pathsApiV1RolesGetParametersQuerySortOrderValues: ReadonlyArray<FlattenedDeepRequired<paths>["/api/v1/roles"]["get"]["parameters"]["query"]["sortOrder"]> = ["asc", "desc"];
export const pathsApiV1RolesGetParametersQuerySortByValues: ReadonlyArray<FlattenedDeepRequired<paths>["/api/v1/roles"]["get"]["parameters"]["query"]["sortBy"]> = ["createdAt", "name"];
export const loginDtoTransportValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["LoginDto"]["transport"]> = ["cookie", "header"];
export const sessionUserDtoPreferredLanguageValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["SessionUserDto"]["preferredLanguage"]> = ["en", "es"];
export const sessionDtoPermissionsValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["SessionDto"]["permissions"]> = ["users:read", "users:create", "users:update", "users:delete", "users:assign_roles", "users:suspend", "roles:read", "roles:create", "roles:update", "roles:delete", "files:create", "files:read"];
export const userDtoStatusValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["UserDto"]["status"]> = ["active", "suspended"];
export const userDtoPreferredLanguageValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["UserDto"]["preferredLanguage"]> = ["en", "es"];
export const createUserDtoPreferredLanguageValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["CreateUserDto"]["preferredLanguage"]> = ["en", "es"];
export const updatePreferencesDtoPreferredLanguageValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["UpdatePreferencesDto"]["preferredLanguage"]> = ["en", "es"];
export const roleDtoPermissionsValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["RoleDto"]["permissions"]> = ["users:read", "users:create", "users:update", "users:delete", "users:assign_roles", "users:suspend", "roles:read", "roles:create", "roles:update", "roles:delete", "files:create", "files:read"];
export const createRoleDtoPermissionsValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["CreateRoleDto"]["permissions"]> = ["users:read", "users:create", "users:update", "users:delete", "users:assign_roles", "users:suspend", "roles:read", "roles:create", "roles:update", "roles:delete", "files:create", "files:read"];
export const updateRoleDtoPermissionsValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["UpdateRoleDto"]["permissions"]> = ["users:read", "users:create", "users:update", "users:delete", "users:assign_roles", "users:suspend", "roles:read", "roles:create", "roles:update", "roles:delete", "files:create", "files:read"];
export const requestUploadDtoContentTypeValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["RequestUploadDto"]["contentType"]> = ["image/png", "image/jpeg", "application/pdf"];
